version: '3.8'

services:
  sgt-postgres:
    image: postgres:15-alpine
    container_name: sgt-postgres
    environment:
      POSTGRES_USER: tonsy
      POSTGRES_PASSWORD: Mk98iuiu.
      POSTGRES_DB: sgt_root
    ports:
      - "5432:5432"
    volumes:
      - sgt_pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  sgt-minio:
    image: minio/minio
    container_name: sgt-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sgt_minio_admin
      MINIO_ROOT_PASSWORD: sgt_minio_password
    volumes:
      - sgt_minio_data:/data
    command: server /data --console-address ":9001"

  ai-orchestrator:
    build:
      context: ../../apps/ai-orchestrator
      dockerfile: Dockerfile
    container_name: sgt-ai-orchestrator
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    container_name: sgt-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  sgt-gateway:
    image: nginx:alpine
    container_name: sgt-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sgt-postgres

volumes:
  sgt_pgdata:
  sgt_minio_data:
